name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Make gradlew executable
      run: chmod +x gradlew
  
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Semgrep (SAST)
      run: |
        pip install semgrep
        semgrep scan --config auto .
    
    - name: Install OWASP Dependency Check
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check.zip -d dependency-check
        chmod +x dependency-check/dependency-check/bin/dependency-check.sh

    - name: Run OWASP Dependency Check
      run: |
        dependency-check/dependency-check/bin/dependency-check.sh \
          --project "SelfServiceCheckout" \
          --scan src/main/java \
          --format HTML \
          --out dependency-check-report

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: dependency-check-report


    # - name: Run Trivy (Container Security)
    #   run: |
    #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    #     docker build -t selfservicecheckout .
    #     trivy image selfservicecheckout

    # - name: Run OWASP ZAP (DAST)
    #   run: |
    #     docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080 -r zap-report.html || true
