name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  semgrep-security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Install and run Semgrep
      run: |
        pip install semgrep
        semgrep scan --config auto --sarif --output semgrep.sarif .

    - name: Upload Semgrep SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
