name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - run: chmod +x gradlew
    - run: ./gradlew build

    # Semgrep
    - run: |
        pip install semgrep
        semgrep scan --config auto --sarif --output semgrep.sarif .
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif

    # Dependency-Check
    - run: |
        curl -sSL -o dc.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip -q dc.zip -d dc
        chmod +x dc/dependency-check/bin/dependency-check.sh
        mkdir -p reports
        dc/dependency-check/bin/dependency-check.sh \
          --project "SelfServiceCheckout" \
          --scan "." \
          --format "HTML" \
          --format "SARIF" \
          --out reports
    - uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports

    # Gitleaks
    - run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        ./gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif --redact
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: gitleaks.sarif

    # Trivy
    - run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        trivy fs --security-checks vuln,secret,config --format sarif --output trivy.sarif .
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy.sarif

  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: github/codeql-action/init@v3
      with:
        languages: java
        build-mode: none
    - uses: github/codeql-action/analyze@v3
