name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - run: chmod +x gradlew
    - run: ./gradlew build

    # Semgrep
    - run: |
        pip install semgrep
        semgrep scan --config auto --sarif --output semgrep.sarif .
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
#Gitleaks
    - uses: gitleaks/gitleaks-action@v2
      with:
        args: detect --source . --report-format sarif --report-path gitleaks.sarif --redact

    # Trivy
    - run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        trivy fs --security-checks vuln,secret,config --format sarif --output trivy.sarif .
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy.sarif

  codeql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: github/codeql-action/init@v3
      with:
        languages: java
        build-mode: none
    - uses: github/codeql-action/analyze@v3
